// Panels
export const SELECT_ACTIVE_PANEL = "SELECT_ACTIVE_PANEL"
export const SELECT_EVENT = "SELECT_EVENT"
export const SELECT_CREATE_NEW_EVENT = "SELECT_CREATE_NEW_EVENT"

// Page
export const SELECT_ACTIVE_PAGE = "SELECT_ACTIVE_PAGE"

// Auth
export const AUTH_SIGNUP = "AUTH_SIGNUP"
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS"
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL"
export const RESET_FAILED_TO_SIGNUP = "RESET_FAILED_TO_SIGNUP"
export const AUTH_SIGNIN = "AUTH_SIGNIN"
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS"
export const AUTH_SIGNIN_FAIL = "AUTH_SIGNIN_FAIL"
export const AUTH_SIGNOUT = "AUTH_SIGNOUT"
export const AUTH_SIGNOUT_SUCCESS = "AUTH_SIGNOUT_SUCCESS"
export const RECEIVE_SOCKET = "RECEIVE_SOCKET"


// Event
export const REMOVE_EVENT = "REMOVE_EVENT"
export const UPDATED_TOTAL = "UPDATED_TOTAL"
